version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: todo.database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Database@2024
      - MYSQL_DATABASE=todolist
    volumes:
      - ./data/mysql/data:/var/lib/mysql