version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: todo.database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Database@2024
      - MYSQL_DATABASE=todolist
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    networks:
      - todo-net

  server:
    container_name: todo.backend
    build: 
      context: ./ToDo-List-API
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - todo-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/todolist?allowPublicKeyRetrieval=true
    depends_on:
      - mysql
    volumes:
      - ./data/api/m2:/root/.m2

  frontend:
    container_name: toto.frontend
    build: 
      context: ./ToDo-List-Frontend
      dockerfile: Dockerfile
    volumes:
      - './ToDo-List-Frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 9999:9999
    environment:
      - VITE_API_URL=http://server:8080
    networks:
      - todo-net
    depends_on:
      - server

networks:
  todo-net:
    driver: bridge