version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: todo.database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Database@2024
      - MYSQL_DATABASE=todolist
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    networks:
      - todo-net

  frontend:
    container_name: toto.frontend
    build: 
      context: ./ToDo-List-Frontend
      dockerfile: Dockerfile
    volumes:
      - './ToDo-List-Frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - todo-net
    depends_on:
      - mysql
    entrypoint: 'npm run dev'

networks:
  todo-net:
    driver: bridge